// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdmissibilityContract } from "./AdmissibilityContract";
import type { MissionStageName } from "./MissionStageName";

export type ActivatePrincipalResponseContract = { missionId: string, missionReceiptId: string, principalActivationReceiptId: string, principalId: string, profileHash: string, chainHead: string, finalStage: MissionStageName, admissibility: AdmissibilityContract, cache_warning: string | null, };
