// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdmissibilityContract } from "./AdmissibilityContract";

export type ErrorBodyContract = { code: string, message: string, domain: string, admissibility: AdmissibilityContract | null, };
