// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Canonical string name for a `MissionStage` at the HTTP boundary.
 */
export type MissionStageName = "Intent" | "Mission" | "Claim" | "Admissibility" | "Execution" | "Receipt" | "Canonicalization" | "Replayability" | "Reflex";
