// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdmissibilityContract } from "./AdmissibilityContract";
import type { OrganizeEntryContract } from "./OrganizeEntryContract";

export type OrganizeResponseContract = { missionId: string, missionReceiptId: string, organizeReceiptId: string, chainHead: string, path: string, listingDigest: string, fileCount: number, dirCount: number, entryCount: number, entries: Array<OrganizeEntryContract>, timestampNs: bigint, admissibility: AdmissibilityContract, };
