// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PoiEntryContract = { receiptId: string, receiptKindByte: number, receiptKindName: string, qualityScore: number, gateMinScore: number, entryCount: number, impactScore: number, timestampNs: bigint, principal_id: string | null, };
