// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Effects this request performed. All false by construction for a GET.
 */
export type PrincipalOperationEffectsContract = { mutationPerformed: boolean, activationPerformed: boolean, witnessIssued: boolean, poiMinted: boolean, soakStarted: boolean, };
