// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Fail-closed verdict ladder. First match wins; every non-`Verified`
 * value leaves `verified_identity` null.
 */
export type PrincipalIdentityStatusVerdict = "ABSENT" | "PROFILE_PRESENT_UNVERIFIED" | "CHAIN_DURABLE_ONLY" | "CHAIN_PAYLOAD_UNAVAILABLE" | "CHAIN_BINDING_MISMATCH" | "VERIFIED";
