// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Constitutional policy, NOT observed runtime state. Deliberately not
 * named `activation_gate`: that name is reserved until the endpoint
 * actually reads a runtime-owned gate. Shipping a compile-time constant
 * under an observation-shaped name is the defect this avoids.
 */
export type PrincipalAuthorityPolicyContract = { activationRequires: string, 
/**
 * Always zero for this read-only surface. `i32` deliberately, not `i64`:
 * ts-rs maps 64-bit ints to `bigint`, which would force every TypeScript
 * consumer into BigInt handling for a value that is constant zero.
 */
authorityDelta: number, };
