// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrincipalAuthorityPolicyContract } from "./PrincipalAuthorityPolicyContract";
import type { PrincipalEvidenceStateContract } from "./PrincipalEvidenceStateContract";
import type { PrincipalIdentityStatusVerdict } from "./PrincipalIdentityStatusVerdict";
import type { PrincipalOperationEffectsContract } from "./PrincipalOperationEffectsContract";
import type { VerifiedPrincipalIdentityContract } from "./VerifiedPrincipalIdentityContract";

/**
 * `GET /principal/status` wire contract.
 */
export type PrincipalIdentityStatusContract = { schema: string, runtimeDomain: string, verdict: PrincipalIdentityStatusVerdict, identityVerified: boolean, bridgeEligible: boolean, verifiedIdentity: VerifiedPrincipalIdentityContract | null, evidenceState: PrincipalEvidenceStateContract, chainHead: string, chainLength: number, authorityPolicy: PrincipalAuthorityPolicyContract, operationEffects: PrincipalOperationEffectsContract, reasonCodes: Array<string>, };
