// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What was actually observed, independent of the verdict. A reader can
 * reconstruct why a verdict was reached without trusting the verdict.
 */
export type PrincipalEvidenceStateContract = { profilePresent: boolean, activeChainRecordFound: boolean, durableReceiptMetadataFound: boolean, canonicalPayloadAvailable: boolean, chainContinuityVerified: boolean, };
