// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UrpBucketContract } from "./UrpBucketContract";

export type UrpViewContract = { totalCount: number, allowlistedCount: number, buckets: Array<UrpBucketContract>, };
