// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Sealed identity fields, populated **only** for `Verified`. Cache data
 * never occupies these fields.
 */
export type VerifiedPrincipalIdentityContract = { principalId: string, principalProfileHash: string, nodePubkey: string, activationReceiptRef: string, receiptId: string, timestampNs: bigint, prevChain: string, };
