#!/usr/bin/env python3
"""Generate a private-pilot evidence pack from local Node0 code paths.

Truth label: MEASURED_LOCAL_ARTIFACT.

This script produces *local* artifacts only:
- A signed handshake JSON (Node0 → peer) generated by `Node0StandaloneManager`.
- A tampered variant (to demonstrate fail-closed verification).
- Verification reports for both.
- A small evidence receipt containing SHA-256 digests of the generated files.

Non-claims:
- This does NOT prove multi-device execution, networked URP membership, SAT-5
  coordination, open discovery, or production federation.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import secrets
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric import ed25519

# Allow running as a direct script (python scripts/ops/generate_private_pilot_evidence_pack.py)
# from within a worktree. Without this, `scripts.*` imports fail because sys.path[0]
# points at scripts/ops/.
import sys as _sys

_REPO_ROOT = Path(__file__).resolve().parents[2]
if str(_REPO_ROOT) not in _sys.path:
    _sys.path.insert(0, str(_REPO_ROOT))

from scripts.node0_standalone import Node0StandaloneManager  # noqa: E402


def _sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def _canonical_json_bytes(payload: Any) -> bytes:
    return json.dumps(payload, sort_keys=True, separators=(",", ":")).encode("utf-8")


def _sha256_json(payload: Any) -> str:
    return hashlib.sha256(_canonical_json_bytes(payload)).hexdigest()


def _new_private_key_hex() -> str:
    key = ed25519.Ed25519PrivateKey.generate()
    return key.private_bytes(
        encoding=serialization.Encoding.Raw,
        format=serialization.PrivateFormat.Raw,
        encryption_algorithm=serialization.NoEncryption(),
    ).hex()


@dataclass(frozen=True)
class EvidencePaths:
    handshake: Path
    tampered: Path
    verify_ok: Path
    verify_tampered: Path
    receipt: Path


def generate_evidence_pack(
    *,
    project_root: Path,
    out_dir: Path,
    peer_node_id: str,
    peer_address: str,
    operator: str,
) -> EvidencePaths:
    out_dir.mkdir(parents=True, exist_ok=True)

    manager = Node0StandaloneManager(project_root=project_root)

    signer_private = _new_private_key_hex()
    peer_private = _new_private_key_hex()
    peer_public = manager._ed25519_public_key_hex(peer_private)

    handshake_path = out_dir / "node0-private-pilot-handshake.json"
    tampered_path = out_dir / "node0-private-pilot-handshake-tampered.json"
    verify_ok_path = out_dir / "node0-private-pilot-verification-report.json"
    verify_tampered_path = out_dir / "node0-private-pilot-verification-report-tampered.json"
    receipt_path = out_dir / "node0-private-pilot-evidence-receipt.json"

    # 1) Create signed handshake artifact.
    manager.create_pilot_handshake(
        peer_node_id=peer_node_id,
        peer_public_key=peer_public,
        peer_address=peer_address,
        operator=operator,
        private_key_hex=signer_private,
        out_path=handshake_path,
        previous_receipt_hash=hashlib.sha256(secrets.token_bytes(16)).hexdigest(),
    )

    # 2) Verify valid artifact.
    verify_ok = manager.verify_pilot_handshake(handshake_path)
    verify_ok_path.write_text(json.dumps(verify_ok, indent=2) + "\n", encoding="utf-8")

    # 3) Tamper artifact (payload field) to ensure verification fails closed.
    tampered = json.loads(handshake_path.read_text(encoding="utf-8"))
    tampered["payload"]["peer_address"] = "127.0.0.1:9999"
    tampered_path.write_text(json.dumps(tampered, indent=2) + "\n", encoding="utf-8")

    verify_tampered = manager.verify_pilot_handshake(tampered_path)
    verify_tampered_path.write_text(
        json.dumps(verify_tampered, indent=2) + "\n", encoding="utf-8"
    )

    # 4) Evidence receipt: content-addressed file hashes + summary.
    receipt = {
        "schema_version": "1.0.0",
        "truth_label": "MEASURED_LOCAL_ARTIFACT",
        "scope": "node0_private_pilot_handshake_local_only",
        "non_claims": [
            "no_multi_device_proof",
            "no_network_transport_proof",
            "no_urp_bootnode_proof",
            "no_sat_coordination_proof",
            "no_production_federation_claim",
        ],
        "inputs": {
            "project_root": str(project_root),
            "peer_node_id": peer_node_id,
            "peer_address": peer_address,
            "operator": operator,
        },
        "artifacts": {
            "handshake": {"path": str(handshake_path), "sha256": _sha256_file(handshake_path)},
            "tampered": {"path": str(tampered_path), "sha256": _sha256_file(tampered_path)},
            "verify_ok": {"path": str(verify_ok_path), "sha256": _sha256_file(verify_ok_path)},
            "verify_tampered": {
                "path": str(verify_tampered_path),
                "sha256": _sha256_file(verify_tampered_path),
            },
        },
        "verification": {
            "valid_artifact": verify_ok,
            "tampered_artifact": verify_tampered,
        },
    }
    receipt["receipt_sha256"] = _sha256_json(receipt)
    receipt_path.write_text(json.dumps(receipt, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    return EvidencePaths(
        handshake=handshake_path,
        tampered=tampered_path,
        verify_ok=verify_ok_path,
        verify_tampered=verify_tampered_path,
        receipt=receipt_path,
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--project-root",
        type=Path,
        default=Path(__file__).resolve().parents[2],
        help="Repo root (default: inferred from this script location).",
    )
    parser.add_argument(
        "--out-dir",
        type=Path,
        default=Path(__file__).resolve().parents[2] / "artifacts" / "proofs",
        help="Output directory for evidence artifacts (default: artifacts/proofs).",
    )
    parser.add_argument("--peer-node-id", default="node1-pilot", help="Peer node id label.")
    parser.add_argument("--peer-address", default="127.0.0.1:9749", help="Peer address label.")
    parser.add_argument("--operator", default="operator", help="Operator label.")
    args = parser.parse_args(argv)

    paths = generate_evidence_pack(
        project_root=args.project_root,
        out_dir=args.out_dir,
        peer_node_id=args.peer_node_id,
        peer_address=args.peer_address,
        operator=args.operator,
    )
    print("[pilot-evidence] wrote:")
    for p in (paths.handshake, paths.tampered, paths.verify_ok, paths.verify_tampered, paths.receipt):
        print(f"  - {p}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

