//! Meta-Constitution — Constitutional Evolution Protocol
//!
//! Implements versioned constitutional amendments with evidence-backed proposals.
//! The Constitution is no longer static: it evolves monotonically upward based
//! on proven agent performance.
//!
//! # Amendment Rules
//!
//! 1. Requires `improvement_streak > threshold` (default 20)
//! 2. Requires `ihsan_ema > STRICT_IHSAN_THRESHOLD` (0.99)
//! 3. Floor can only increase (monotonic improvement)
//! 4. Maximum step size: +0.01 per amendment
//! 5. Floor capped at 0.99 (asymptotic excellence)
//! 6. All amendments carry BLAKE3 evidence hash
//!
//! # Standing on Giants
//!
//! - **SAHOO et al.** (2603.06333): Safeguarded Recursive Self-Improvement
//! - **Al-Ghazali**: Ihsan as constitutional constraint
//! - **Jefferson**: Constitutional amendment process with deliberation
//! - **Arrow**: Monotonic social choice functions
//! - **Deming**: Continuous improvement (Kaizen)

use blake3::Hasher;
use serde::{Deserialize, Serialize};

use super::autopoiesis::AutopoieticState;
use crate::{IHSAN_THRESHOLD, STRICT_IHSAN_THRESHOLD};

/// Domain separation prefix for constitutional evolution hashes.
const META_CONSTITUTION_DOMAIN: &[u8] = b"bizra-meta-constitution-v1:";

/// Default minimum improvement streak required for amendment eligibility.
const DEFAULT_AMENDMENT_THRESHOLD_STREAK: u32 = 20;

/// Maximum Ihsan floor step per amendment (+0.01).
const DEFAULT_AMENDMENT_MAX_STEP: f64 = 0.01;

/// Absolute cap on Ihsan floor (asymptotic excellence).
const IHSAN_FLOOR_CAP: f64 = 0.99;

/// Constitutional Era — A versioned snapshot of constitutional parameters.
///
/// Each era represents a stable configuration of thresholds. Eras form
/// a monotonically increasing sequence: era N+1 has floors >= era N.
///
/// # Invariants
///
/// - `ihsan_floor >= IHSAN_THRESHOLD` (never below production minimum)
/// - `snr_floor >= SNR_THRESHOLD` (never below production minimum)
/// - `version` is monotonically increasing
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct ConstitutionalEra {
    /// Era version number (monotonically increasing).
    pub version: u32,
    /// Ihsan floor for this era.
    pub ihsan_floor: f64,
    /// SNR floor for this era.
    pub snr_floor: f64,
    /// Timestamp when this era was activated (Unix epoch seconds).
    pub activated_at: u64,
    /// BLAKE3 hash of the evidence that justified this era.
    pub evidence_hash: [u8; 32],
}

/// Amendment Proposal — A formal proposal to evolve the constitution.
///
/// Proposals are generated by the autopoietic loop when sustained
/// excellence (long improvement streak + high Ihsan EMA) is demonstrated.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct AmendmentProposal {
    /// Target era version.
    pub target_version: u32,
    /// Proposed new Ihsan floor.
    pub proposed_ihsan_floor: f64,
    /// Proposed new SNR floor.
    pub proposed_snr_floor: f64,
    /// BLAKE3 hash of the evidence (autopoietic state + convergence report).
    pub evidence_hash: [u8; 32],
    /// Human-readable justification.
    pub justification: String,
}

/// Amendment Verdict — The outcome of evaluating an amendment proposal.
#[derive(Clone, Debug)]
pub enum AmendmentVerdict {
    /// Amendment ratified — new era activated.
    Ratified {
        /// The newly created constitutional era.
        new_era: ConstitutionalEra,
    },
    /// Amendment rejected — reason provided.
    Rejected {
        /// Reason for rejection.
        reason: String,
    },
}

/// Meta-Constitution — Constitutional governance with versioned evolution.
///
/// Wraps the base Constitution with an amendment protocol that allows
/// the system to raise its own standards based on proven performance.
///
/// # Design Principles
///
/// - **Monotonic**: Floors only increase, never decrease
/// - **Evidence-based**: Amendments require cryptographic proof of sustained excellence
/// - **Bounded**: Maximum +0.01 step per amendment, capped at 0.99
/// - **Deliberate**: High threshold (streak > 20, Ihsan EMA > 0.99)
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct MetaConstitution {
    /// Current active era.
    pub current_era: ConstitutionalEra,
    /// History of all previous eras.
    pub era_history: Vec<ConstitutionalEra>,
    /// Minimum improvement streak required for amendment eligibility.
    pub amendment_threshold_streak: u32,
    /// Maximum Ihsan floor step per amendment.
    pub amendment_max_step: f64,
}

impl MetaConstitution {
    /// Create a new meta-constitution with the genesis era.
    ///
    /// The genesis era uses the production `IHSAN_THRESHOLD` and `SNR_THRESHOLD`
    /// as initial floors.
    pub fn new() -> Self {
        let genesis_era = ConstitutionalEra {
            version: 1,
            ihsan_floor: IHSAN_THRESHOLD,
            snr_floor: crate::SNR_THRESHOLD,
            activated_at: now_unix_secs(),
            evidence_hash: [0u8; 32], // Genesis has no prior evidence
        };

        Self {
            current_era: genesis_era,
            era_history: Vec::new(),
            amendment_threshold_streak: DEFAULT_AMENDMENT_THRESHOLD_STREAK,
            amendment_max_step: DEFAULT_AMENDMENT_MAX_STEP,
        }
    }

    /// Propose a constitutional amendment based on autopoietic state.
    ///
    /// Returns `Some(AmendmentProposal)` if the agent's state qualifies for
    /// an amendment, or `None` if conditions are not met.
    ///
    /// # Qualification Criteria
    ///
    /// - `state.improvement_streak > amendment_threshold_streak`
    /// - `state.ihsan_ema > STRICT_IHSAN_THRESHOLD`
    pub fn propose_amendment(&self, state: &AutopoieticState) -> Option<AmendmentProposal> {
        // Check qualification
        if state.improvement_streak <= self.amendment_threshold_streak {
            return None;
        }
        if state.ihsan_ema <= STRICT_IHSAN_THRESHOLD {
            return None;
        }

        // Calculate proposed new floor
        let proposed_ihsan_floor =
            (self.current_era.ihsan_floor + self.amendment_max_step).min(IHSAN_FLOOR_CAP);

        // Don't propose if already at cap
        if (proposed_ihsan_floor - self.current_era.ihsan_floor).abs() < f64::EPSILON {
            return None;
        }

        // Compute evidence hash from autopoietic state
        let evidence_hash = compute_evidence_hash(state);

        Some(AmendmentProposal {
            target_version: self.current_era.version + 1,
            proposed_ihsan_floor,
            proposed_snr_floor: self.current_era.snr_floor, // SNR floor unchanged for now
            evidence_hash,
            justification: format!(
                "Sustained excellence: streak={}, ihsan_ema={:.4}, cycles={}",
                state.improvement_streak, state.ihsan_ema, state.total_cycles
            ),
        })
    }

    /// Evaluate an amendment proposal and return a verdict.
    ///
    /// # Validation Rules
    ///
    /// 1. Target version must be current + 1
    /// 2. Proposed Ihsan floor must be > current floor (monotonic)
    /// 3. Step size must be <= `amendment_max_step`
    /// 4. Proposed floor must be <= `IHSAN_FLOOR_CAP`
    /// 5. Evidence hash must not be all zeros
    pub fn evaluate_amendment(&mut self, proposal: &AmendmentProposal) -> AmendmentVerdict {
        // Check version continuity
        if proposal.target_version != self.current_era.version + 1 {
            return AmendmentVerdict::Rejected {
                reason: format!(
                    "Version mismatch: expected {}, got {}",
                    self.current_era.version + 1,
                    proposal.target_version
                ),
            };
        }

        // Check monotonic increase
        if proposal.proposed_ihsan_floor <= self.current_era.ihsan_floor {
            return AmendmentVerdict::Rejected {
                reason: format!(
                    "Ihsan floor must increase: current={:.4}, proposed={:.4}",
                    self.current_era.ihsan_floor, proposal.proposed_ihsan_floor
                ),
            };
        }

        // Check step size
        let step = proposal.proposed_ihsan_floor - self.current_era.ihsan_floor;
        if step > self.amendment_max_step + f64::EPSILON {
            return AmendmentVerdict::Rejected {
                reason: format!(
                    "Step size {step:.4} exceeds maximum {:.4}",
                    self.amendment_max_step
                ),
            };
        }

        // Check cap
        if proposal.proposed_ihsan_floor > IHSAN_FLOOR_CAP + f64::EPSILON {
            return AmendmentVerdict::Rejected {
                reason: format!(
                    "Proposed floor {:.4} exceeds cap {IHSAN_FLOOR_CAP:.4}",
                    proposal.proposed_ihsan_floor
                ),
            };
        }

        // Check evidence hash is non-trivial
        if proposal.evidence_hash == [0u8; 32] {
            return AmendmentVerdict::Rejected {
                reason: "Evidence hash cannot be all zeros".to_string(),
            };
        }

        // Ratify: archive current era and activate new era
        let new_era = ConstitutionalEra {
            version: proposal.target_version,
            ihsan_floor: proposal.proposed_ihsan_floor,
            snr_floor: proposal.proposed_snr_floor,
            activated_at: now_unix_secs(),
            evidence_hash: proposal.evidence_hash,
        };

        self.era_history.push(self.current_era.clone());
        self.current_era = new_era.clone();

        AmendmentVerdict::Ratified { new_era }
    }

    /// Get the current Ihsan floor.
    pub fn current_ihsan_floor(&self) -> f64 {
        self.current_era.ihsan_floor
    }

    /// Get the full era history (including archived eras, not the current one).
    pub fn eras(&self) -> &[ConstitutionalEra] {
        &self.era_history
    }
}

impl Default for MetaConstitution {
    fn default() -> Self {
        Self::new()
    }
}

/// Compute a BLAKE3 evidence hash from an autopoietic state.
///
/// Hashes the key invariants: cycle_count, ihsan_ema, total_seed,
/// improvement_streak.
fn compute_evidence_hash(state: &AutopoieticState) -> [u8; 32] {
    let mut hasher = Hasher::new();
    hasher.update(META_CONSTITUTION_DOMAIN);
    hasher.update(&state.cycle_count.to_le_bytes());
    hasher.update(&state.ihsan_ema.to_le_bytes());
    hasher.update(&state.total_seed.to_le_bytes());
    hasher.update(&state.improvement_streak.to_le_bytes());
    *hasher.finalize().as_bytes()
}

/// Get current Unix timestamp in seconds.
fn now_unix_secs() -> u64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs()
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Helper: create a state with a long improvement streak and high Ihsan.
    fn high_performing_state() -> AutopoieticState {
        let mut state = AutopoieticState::new();
        // Run many high-quality cycles to build streak and EMA
        for _ in 0..50 {
            state.execute_cycle(0.998, 0.95);
        }
        state
    }

    #[test]
    fn test_amendment_rejected_low_streak() {
        let meta = MetaConstitution::new();

        // State with low streak
        let mut state = AutopoieticState::new();
        for _ in 0..5 {
            state.execute_cycle(0.998, 0.95);
        }

        let proposal = meta.propose_amendment(&state);
        assert!(
            proposal.is_none(),
            "Should not propose amendment with low streak ({})",
            state.improvement_streak
        );
    }

    #[test]
    fn test_amendment_ratified() {
        let mut meta = MetaConstitution::new();
        let state = high_performing_state();

        // Verify the state qualifies
        assert!(
            state.improvement_streak > meta.amendment_threshold_streak,
            "Streak {} should exceed threshold {}",
            state.improvement_streak,
            meta.amendment_threshold_streak
        );

        let proposal = meta.propose_amendment(&state);
        assert!(
            proposal.is_some(),
            "Should propose amendment for high-performing state"
        );

        let proposal = proposal.unwrap();
        assert!(
            proposal.proposed_ihsan_floor > meta.current_ihsan_floor(),
            "Proposed floor should exceed current"
        );

        let old_floor = meta.current_ihsan_floor();
        let verdict = meta.evaluate_amendment(&proposal);

        assert!(
            matches!(verdict, AmendmentVerdict::Ratified { .. }),
            "Amendment should be ratified"
        );
        assert!(
            meta.current_ihsan_floor() > old_floor,
            "Floor should have increased"
        );
        assert_eq!(meta.eras().len(), 1, "Should have one archived era");
    }

    #[test]
    fn test_monotonic_floor() {
        let mut meta = MetaConstitution::new();
        let initial_floor = meta.current_ihsan_floor();

        // Apply multiple amendments
        for i in 0..5 {
            let state = high_performing_state();
            if let Some(proposal) = meta.propose_amendment(&state) {
                let verdict = meta.evaluate_amendment(&proposal);
                match &verdict {
                    AmendmentVerdict::Ratified { new_era } => {
                        assert!(
                            new_era.ihsan_floor >= initial_floor,
                            "Floor must never decrease below initial (step {i})"
                        );
                    }
                    AmendmentVerdict::Rejected { .. } => {
                        // Rejection is acceptable (e.g., at cap)
                    }
                }
            }
        }

        // Final floor must be >= initial
        assert!(
            meta.current_ihsan_floor() >= initial_floor,
            "Final floor {:.4} must be >= initial {initial_floor:.4}",
            meta.current_ihsan_floor()
        );
    }

    #[test]
    fn test_floor_capped_at_099() {
        let mut meta = MetaConstitution::new();

        // Force many amendments to approach cap
        for _ in 0..100 {
            let state = high_performing_state();
            if let Some(proposal) = meta.propose_amendment(&state) {
                meta.evaluate_amendment(&proposal);
            }
        }

        assert!(
            meta.current_ihsan_floor() <= IHSAN_FLOOR_CAP + f64::EPSILON,
            "Floor {:.4} must not exceed cap {IHSAN_FLOOR_CAP:.4}",
            meta.current_ihsan_floor()
        );
    }

    #[test]
    fn test_version_mismatch_rejected() {
        let mut meta = MetaConstitution::new();

        let bad_proposal = AmendmentProposal {
            target_version: 99, // Wrong version
            proposed_ihsan_floor: meta.current_ihsan_floor() + 0.01,
            proposed_snr_floor: meta.current_era.snr_floor,
            evidence_hash: [1u8; 32],
            justification: "test".to_string(),
        };

        let verdict = meta.evaluate_amendment(&bad_proposal);
        assert!(
            matches!(verdict, AmendmentVerdict::Rejected { .. }),
            "Version mismatch should be rejected"
        );
    }

    #[test]
    fn test_zero_evidence_rejected() {
        let mut meta = MetaConstitution::new();

        let bad_proposal = AmendmentProposal {
            target_version: 2,
            proposed_ihsan_floor: meta.current_ihsan_floor() + 0.01,
            proposed_snr_floor: meta.current_era.snr_floor,
            evidence_hash: [0u8; 32], // All zeros
            justification: "test".to_string(),
        };

        let verdict = meta.evaluate_amendment(&bad_proposal);
        assert!(
            matches!(verdict, AmendmentVerdict::Rejected { .. }),
            "Zero evidence hash should be rejected"
        );
    }
}
