/**
 * Canonical Semantics Layer (CSL) — TypeScript-side drift tests.
 *
 * The Python source of truth lives in core/dema/csl/labels.py. The on-disk
 * TS mirror at src/lib/dema-csl.ts is generated by
 * `python scripts/dema/dema_csl.py emit-ts --write`. The Python test
 * test_typescript_mirror_matches_python asserts the TS file is in sync
 * with the Python emitter.
 *
 * These TS-side tests independently lock the EXPECTED string values so
 * that even if the generator regenerated wrong content, the contract still
 * fails loudly.
 */

import { describe, expect, it } from "vitest";

import {
  APPROVAL_STATUSES,
  CSL_SCHEMA_VERSION,
  DECISION_VERDICTS,
  DISPLAY_TRUTH_LABELS,
  MISSION_TRUTH_LABELS,
  RECEIPT_TRUTH_LABELS,
  RISK_LEVELS,
} from "../src/lib/dema-csl";

describe("CSL — canonical labels", () => {
  it("schema version is set", () => {
    expect(CSL_SCHEMA_VERSION).toBe("0.1.0");
  });

  it("RECEIPT_TRUTH_LABELS = MEASURED|DERIVED|PLANNED|SANDBOX", () => {
    expect([...RECEIPT_TRUTH_LABELS]).toEqual([
      "MEASURED",
      "DERIVED",
      "PLANNED",
      "SANDBOX",
    ]);
  });

  it("DISPLAY_TRUTH_LABELS adds exactly UNKNOWN to the receipt set", () => {
    expect([...DISPLAY_TRUTH_LABELS]).toEqual([
      "MEASURED",
      "DERIVED",
      "PLANNED",
      "SANDBOX",
      "UNKNOWN",
    ]);
    const extra = [...DISPLAY_TRUTH_LABELS].filter(
      (v) => !(RECEIPT_TRUTH_LABELS as readonly string[]).includes(v),
    );
    expect(extra).toEqual(["UNKNOWN"]);
  });

  it("MISSION_TRUTH_LABELS == DISPLAY_TRUTH_LABELS", () => {
    expect([...MISSION_TRUTH_LABELS]).toEqual([...DISPLAY_TRUTH_LABELS]);
  });

  it("RISK_LEVELS = low|medium|high", () => {
    expect([...RISK_LEVELS]).toEqual(["low", "medium", "high"]);
  });

  it("APPROVAL_STATUSES = granted|pending|n/a|denied", () => {
    expect([...APPROVAL_STATUSES]).toEqual([
      "granted",
      "pending",
      "n/a",
      "denied",
    ]);
  });

  it("DECISION_VERDICTS = auto_low_risk|notify|require_approval|forbid", () => {
    expect([...DECISION_VERDICTS]).toEqual([
      "auto_low_risk",
      "notify",
      "require_approval",
      "forbid",
    ]);
  });
});

describe("CSL — Goal-card consumer alignment", () => {
  /**
   * goal-truth-badge.tsx defines its own GoalTruthLabel union literal. It
   * predates CSL; the v0.1 contract is that every value the goal card
   * uses is a member of DISPLAY_TRUTH_LABELS. v0.2 will swap the local
   * union for `DisplayTruthLabel` from CSL.
   */
  it("every label the Goal card may render is in DISPLAY_TRUTH_LABELS", () => {
    const goalCardLabels = ["MEASURED", "DERIVED", "PLANNED", "UNKNOWN"];
    const csl = new Set<string>(DISPLAY_TRUTH_LABELS as readonly string[]);
    for (const label of goalCardLabels) {
      expect(csl.has(label)).toBe(true);
    }
  });
});
