#!/usr/bin/env bash
# ==============================================================================
# BIZRA NODE0 — Install systemd services with native path overrides
# ==============================================================================
#
# Installs the canonical .service templates from deploy/node0/systemd-services/
# AND creates drop-in overrides that patch paths for native Ubuntu (not WSL).
#
# This does NOT modify the .service template files. It creates systemd
# drop-in directories with override.conf files that replace the WSL paths.
#
# Usage:
#   sudo ./install_node0_services.sh
#
# ==============================================================================

set -euo pipefail

readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly REPO_ROOT="${SCRIPT_DIR}/../.."
readonly SERVICE_DIR="${SCRIPT_DIR}/systemd-services"
readonly SYSTEMD_DIR="/etc/systemd/system"
readonly ENV_SOURCE="${SCRIPT_DIR}/node0.env"
readonly ENV_DEST="/etc/bizra/node0.env"

BIZRA_ROOT="/data/bizra/repos/bizra-data-lake"
VENV="${BIZRA_ROOT}/.venv"

# Colors
G='\033[0;32m' R='\033[0;31m' Y='\033[0;33m' N='\033[0m'

log() { echo -e "${G}[+]${N} $*"; }
warn() { echo -e "${Y}[!]${N} $*"; }
err() { echo -e "${R}[-]${N} $*" >&2; exit 1; }

# Must be root
[[ "$(id -u)" -eq 0 ]] || err "Must run as root (sudo)"

# ==============================================================================
# 1. Create bizra user/group if needed
# ==============================================================================

if ! id -u bizra &>/dev/null; then
    log "Creating bizra system user"
    useradd --system --home-dir "${BIZRA_ROOT}" --shell /usr/sbin/nologin bizra
fi

# ==============================================================================
# 2. Create directories
# ==============================================================================

log "Creating directories"
mkdir -p /etc/bizra /var/log/bizra /var/run/bizra
mkdir -p "${BIZRA_ROOT}/sovereign_state" "${BIZRA_ROOT}/checkpoints"

# ==============================================================================
# 3. Install environment file
# ==============================================================================

log "Installing environment file to ${ENV_DEST}"
cp "${ENV_SOURCE}" "${ENV_DEST}"
chmod 640 "${ENV_DEST}"
chown root:bizra "${ENV_DEST}"

# ==============================================================================
# 4. Install service templates
# ==============================================================================

log "Installing service templates"
for svc in "${SERVICE_DIR}"/*.service; do
    svc_name="$(basename "$svc")"
    cp "$svc" "${SYSTEMD_DIR}/${svc_name}"
    log "  Installed ${svc_name}"
done

# Also install kernel service
if [[ -f "${SCRIPT_DIR}/bizra-kernel.service" ]]; then
    cp "${SCRIPT_DIR}/bizra-kernel.service" "${SYSTEMD_DIR}/bizra-kernel.service"
    log "  Installed bizra-kernel.service"
fi

# ==============================================================================
# 5. Create drop-in overrides for native paths
# ==============================================================================

log "Creating systemd drop-in overrides for native Ubuntu paths"

# Sovereign override — the main one
SOVEREIGN_DROPIN="${SYSTEMD_DIR}/bizra-sovereign.service.d"
mkdir -p "${SOVEREIGN_DROPIN}"
cat > "${SOVEREIGN_DROPIN}/node0-paths.conf" << EOF
# Auto-generated by install_node0_services.sh
# Overrides WSL /mnt/c/ paths to native Ubuntu paths
[Service]
WorkingDirectory=${BIZRA_ROOT}
Environment="PYTHONPATH=${BIZRA_ROOT}"
Environment="VIRTUAL_ENV=${VENV}"
Environment="PATH=${VENV}/bin:/usr/local/bin:/usr/bin:/bin"
Environment="DATA_LAKE_ROOT=${BIZRA_ROOT}"
Environment="GOLD_PATH=${BIZRA_ROOT}/04_GOLD"
Environment="STATE_PATH=${BIZRA_ROOT}/sovereign_state"
ExecStart=
ExecStart=${VENV}/bin/python -m core.sovereign --mode production --enable-autonomous --ihsan-threshold 0.95 --snr-threshold 0.85 --persist-state
ExecStop=
ExecStop=${VENV}/bin/python -c "import asyncio; from core.sovereign import SovereignRuntime; asyncio.run(SovereignRuntime().shutdown())"
ReadWritePaths=${BIZRA_ROOT}/sovereign_state
ReadWritePaths=${BIZRA_ROOT}/checkpoints
ReadOnlyPaths=${BIZRA_ROOT}
EnvironmentFile=${ENV_DEST}
EOF
log "  Created ${SOVEREIGN_DROPIN}/node0-paths.conf"

# Kernel override
KERNEL_DROPIN="${SYSTEMD_DIR}/bizra-kernel.service.d"
mkdir -p "${KERNEL_DROPIN}"
cat > "${KERNEL_DROPIN}/node0-paths.conf" << EOF
[Service]
WorkingDirectory=${BIZRA_ROOT}
Environment="PYTHONPATH=${BIZRA_ROOT}"
ExecStartPre=
ExecStartPre=${VENV}/bin/python -c "import core.sovereign.kernel_daemon"
ExecStart=
ExecStart=${VENV}/bin/python -m core.sovereign.kernel_daemon
ReadWritePaths=${BIZRA_ROOT}/sovereign_state
ReadWritePaths=${BIZRA_ROOT}/logs
EnvironmentFile=${ENV_DEST}
EOF
log "  Created ${KERNEL_DROPIN}/node0-paths.conf"

# API override (Rust binary — just fix the working directory)
API_DROPIN="${SYSTEMD_DIR}/bizra-api.service.d"
mkdir -p "${API_DROPIN}"
cat > "${API_DROPIN}/node0-paths.conf" << EOF
[Service]
WorkingDirectory=${BIZRA_ROOT}
EnvironmentFile=${ENV_DEST}
EOF
log "  Created ${API_DROPIN}/node0-paths.conf"

# ==============================================================================
# 6. Set permissions
# ==============================================================================

log "Setting permissions"
chown -R bizra:bizra "${BIZRA_ROOT}/sovereign_state" 2>/dev/null || true
chown -R bizra:bizra "${BIZRA_ROOT}/checkpoints" 2>/dev/null || true
chown -R bizra:bizra /var/log/bizra 2>/dev/null || true

# ==============================================================================
# 7. Reload systemd
# ==============================================================================

log "Reloading systemd"
systemctl daemon-reload

# ==============================================================================
# 8. Enable services (don't start yet — activation script does that)
# ==============================================================================

log "Enabling services"
for svc in bizra-sovereign bizra-kernel; do
    systemctl enable "${svc}" 2>/dev/null || warn "Could not enable ${svc}"
done

echo ""
echo "════════════════════════════════════════════════════════════"
echo "  NODE0 systemd services installed"
echo "  Next: run deploy/node0/bizra_node_activate.sh"
echo "════════════════════════════════════════════════════════════"
