#!/usr/bin/env python3
"""
Dependency governance gate for BIZRA.

Checks:
- `pyproject.toml` production dependencies are the authoritative source.
- `requirements.txt` mirrors `pyproject.toml` exactly for production/SBOM use.
- `requirements.lock` is a uv-generated, hash-pinned lock without editable/VCS deps.
- Locked versions for production dependencies satisfy declared constraints.
"""

from __future__ import annotations

import argparse
import difflib
import re
import sys
import tomllib
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

try:
    from packaging.requirements import Requirement
except ImportError as exc:  # pragma: no cover - packaging should exist in CI/dev
    raise RuntimeError(
        "packaging is required for dependency governance checks"
    ) from exc


ROOT = Path(__file__).resolve().parents[1]
PYPROJECT_PATH = ROOT / "pyproject.toml"
REQUIREMENTS_PATH = ROOT / "requirements.txt"
LOCK_PATH = ROOT / "requirements.lock"
LOCK_HEADER_PREFIX = "# This file was autogenerated by uv via the following command:"

LOCK_ENTRY_RE = re.compile(
    r"^([A-Za-z0-9_.-]+)(?:\[[A-Za-z0-9_,.-]+\])?==([^\s\\]+)(?:\s*\\)?$"
)
LOCK_HASH_RE = re.compile(r"^\s*--hash=sha256:")
EDITABLE_OR_VCS_RE = re.compile(r"(?:^-e\s)|(?:git\+)|(?:\s@\s*git\+)")


@dataclass(frozen=True)
class NormalizedRequirement:
    raw: str
    name: str
    extras: tuple[str, ...]
    specifier: str
    marker: str | None
    url: str | None

    @classmethod
    def parse(cls, requirement_text: str) -> "NormalizedRequirement":
        req = Requirement(requirement_text)
        return cls(
            raw=requirement_text,
            name=req.name.lower().replace("_", "-"),
            extras=tuple(sorted(req.extras)),
            specifier=str(req.specifier),
            marker=str(req.marker) if req.marker else None,
            url=req.url,
        )

    def normalized_text(self) -> str:
        extras = f"[{','.join(self.extras)}]" if self.extras else ""
        marker = f"; {self.marker}" if self.marker else ""
        if self.url:
            return f"{self.name}{extras} @ {self.url}{marker}"
        return f"{self.name}{extras}{self.specifier}{marker}"


@dataclass(frozen=True)
class DependencyGovernanceReport:
    issues: tuple[str, ...]

    @property
    def ok(self) -> bool:
        return not self.issues

    def format(self) -> str:
        if self.ok:
            return "No dependency-governance issues."
        return "\n".join(f"- {issue}" for issue in self.issues)


def _clean_requirement_line(line: str) -> str:
    head = line.split("#", 1)[0].strip()
    return head


def load_pyproject_dependencies(pyproject_path: Path) -> list[NormalizedRequirement]:
    with pyproject_path.open("rb") as handle:
        data = tomllib.load(handle)
    deps = data.get("project", {}).get("dependencies", [])
    return [NormalizedRequirement.parse(dep) for dep in deps]


def load_requirements_txt(requirements_path: Path) -> list[NormalizedRequirement]:
    requirements: list[NormalizedRequirement] = []
    for raw_line in requirements_path.read_text(encoding="utf-8").splitlines():
        line = _clean_requirement_line(raw_line)
        if not line:
            continue
        requirements.append(NormalizedRequirement.parse(line))
    return requirements


def _diff_expected_vs_actual(
    expected: Iterable[NormalizedRequirement],
    actual: Iterable[NormalizedRequirement],
) -> str:
    expected_lines = [item.normalized_text() for item in expected]
    actual_lines = [item.normalized_text() for item in actual]
    diff = difflib.unified_diff(
        expected_lines,
        actual_lines,
        fromfile="pyproject.toml",
        tofile="requirements.txt",
        lineterm="",
    )
    return "\n".join(diff)


def _finalize_lock_entry(
    current_name: str | None,
    current_hashes: int,
    issues: list[str],
) -> None:
    if current_name is not None and current_hashes == 0:
        issues.append(f"requirements.lock entry '{current_name}' is not hash-pinned")


def parse_lock_pins(lock_path: Path, issues: list[str]) -> dict[str, str]:
    lines = lock_path.read_text(encoding="utf-8").splitlines()
    if not lines or not lines[0].startswith(LOCK_HEADER_PREFIX):
        issues.append(
            "requirements.lock must be autogenerated by uv and start with the uv header"
        )

    pins: dict[str, str] = {}
    current_name: str | None = None
    current_hashes = 0

    for line in lines:
        if EDITABLE_OR_VCS_RE.search(line):
            issues.append("requirements.lock contains editable or VCS dependencies")

        match = LOCK_ENTRY_RE.match(line)
        if match:
            _finalize_lock_entry(current_name, current_hashes, issues)
            name = match.group(1).lower().replace("_", "-")
            version = match.group(2)
            if name in pins and pins[name] != version:
                issues.append(f"requirements.lock contains duplicate pins for '{name}'")
            pins[name] = version
            current_name = name
            current_hashes = 0
            continue

        if current_name is not None and LOCK_HASH_RE.match(line):
            current_hashes += 1

    _finalize_lock_entry(current_name, current_hashes, issues)
    return pins


def validate_dependency_governance(
    pyproject_path: Path = PYPROJECT_PATH,
    requirements_path: Path = REQUIREMENTS_PATH,
    lock_path: Path = LOCK_PATH,
    *,
    require_lock: bool = True,
) -> DependencyGovernanceReport:
    issues: list[str] = []

    pyproject_deps = load_pyproject_dependencies(pyproject_path)
    requirements_deps = load_requirements_txt(requirements_path)

    if pyproject_deps != requirements_deps:
        diff = _diff_expected_vs_actual(pyproject_deps, requirements_deps)
        issues.append("requirements.txt drifted from pyproject.toml")
        if diff:
            issues.append(diff)

    if require_lock:
        lock_pins = parse_lock_pins(lock_path, issues)
        for dep in pyproject_deps:
            if dep.url:
                issues.append(
                    f"pyproject production dependency '{dep.normalized_text()}' must not be a direct URL dependency"
                )
                continue
            version = lock_pins.get(dep.name)
            if version is None:
                issues.append(
                    f"requirements.lock is missing a pin for production dependency '{dep.name}'"
                )
                continue
            specifier = Requirement(dep.normalized_text()).specifier
            if specifier and not specifier.contains(version, prereleases=True):
                issues.append(
                    "requirements.lock pin "
                    f"'{dep.name}=={version}' violates declared constraint '{dep.normalized_text()}'"
                )

    return DependencyGovernanceReport(issues=tuple(issues))


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--skip-lock",
        action="store_true",
        help="Only validate pyproject.toml vs requirements.txt, skip requirements.lock",
    )
    args = parser.parse_args(argv)

    report = validate_dependency_governance(require_lock=not args.skip_lock)
    if not report.ok:
        print("[DEPENDENCY-GOVERNANCE] FAILED")
        print(report.format())
        return 1

    print("[DEPENDENCY-GOVERNANCE] PASS")
    print("pyproject.toml, requirements.txt, and requirements.lock are aligned.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
