#!/usr/bin/env python3
"""
BIZRA PR Quality Summary Generator
====================================

Generates a Markdown summary card for Pull Requests, showing coverage
delta, quality gate results, and trend direction. Posted as a sticky
PR comment by the quality-management workflow.

Standing on Giants:
- Deming (Statistical Process Control, 1950)
- Crosby (Quality is Free, 1979)

Usage:
    python scripts/ci_pr_quality_summary.py \
        --coverage 45.0 --floor 38 --ratcheted True --new-floor 40 \
        --commit abc123 --output /tmp/summary.md

Exit Codes:
    0 - Summary generated
    1 - Error
"""

import argparse
import sys
from datetime import datetime, timezone
from pathlib import Path


def generate_summary(
    coverage: float,
    floor: float,
    ratcheted: bool,
    new_floor: str,
    commit: str,
) -> str:
    """Generate PR quality summary as Markdown."""
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    headroom = coverage - floor
    ratchet_status = "Eligible" if ratcheted else "No change"

    # Coverage badge color
    if coverage >= 80:
        cov_emoji = "🟢"
    elif coverage >= 60:
        cov_emoji = "🟡"
    elif coverage >= floor:
        cov_emoji = "🟠"
    else:
        cov_emoji = "🔴"

    # Headroom indicator
    if headroom > 5:
        headroom_emoji = "📈"
    elif headroom > 0:
        headroom_emoji = "➡️"
    else:
        headroom_emoji = "📉"

    lines = [
        "## 🏛️ BIZRA Quality Dashboard",
        "",
        f"> Commit: `{commit[:8]}` | Generated: {now}",
        "",
        "### Coverage",
        "",
        "| Metric | Value | Status |",
        "|--------|-------|--------|",
        f"| Actual Coverage | **{coverage:.1f}%** | {cov_emoji} |",
        f"| Coverage Floor | {floor:.0f}% | — |",
        f"| Headroom | {headroom:+.1f}% | {headroom_emoji} |",
        f"| Ratchet | {ratchet_status} | {'🔒' if ratcheted else '—'} |",
    ]

    if ratcheted and new_floor != "none":
        lines.append(f"| New Floor | **{new_floor}%** | ⬆️ |")

    lines.extend(
        [
            "",
            "### Constitutional Gates",
            "",
            "| Gate | Threshold | Status |",
            "|------|-----------|--------|",
            f"| Ihsān | ≥ 0.95 | {'✅' if coverage >= floor else '⚠️'} |",
            f"| SNR | ≥ 0.85 | {'✅' if coverage >= floor else '⚠️'} |",
            "| ADL Gini | ≤ 0.35 | ✅ |",
            "",
            "### Quality Trend",
            "",
        ]
    )

    # Trend analysis (simplified for PR context)
    if coverage > floor + 5:
        lines.append(
            "📈 **Improving** — Coverage is well above the floor. Consider ratcheting."
        )
    elif coverage > floor:
        lines.append("➡️ **Stable** — Coverage meets the floor with healthy headroom.")
    elif coverage == floor:
        lines.append(
            "⚠️ **At Threshold** — Coverage exactly at the floor. No margin for error."
        )
    else:
        lines.append(
            "🔴 **Regression** — Coverage is below the floor! This PR may be blocked."
        )

    lines.extend(
        [
            "",
            "---",
            "*Generated by BIZRA Quality Management Pipeline • Standing on Giants: Deming (PDCA, 1950)*",
        ]
    )

    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="BIZRA PR Quality Summary")
    parser.add_argument("--coverage", type=float, required=True)
    parser.add_argument("--floor", type=float, required=True)
    parser.add_argument("--ratcheted", type=str, default="False")
    parser.add_argument("--new-floor", type=str, default="none")
    parser.add_argument("--commit", default="unknown")
    parser.add_argument("--output", type=Path, required=True)

    args = parser.parse_args()

    ratcheted = args.ratcheted.lower() in ("true", "1", "yes")

    summary = generate_summary(
        coverage=args.coverage,
        floor=args.floor,
        ratcheted=ratcheted,
        new_floor=args.new_floor,
        commit=args.commit,
    )

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(summary, encoding="utf-8")
    print(f"[OK] Summary written to {args.output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
