#Requires -RunAsAdministrator
<#
.SYNOPSIS
    BIZRA Resource Guardian - Installer
.DESCRIPTION
    Sets up:
    1. WSL2 memory cap (.wslconfig)
    2. Scheduled task to run Guardian on login
    3. Disables non-essential Windows features
    4. Power plan optimization
    5. Convenience scripts
#>

param(
    [string]$InstallDir = "$env:USERPROFILE\.bizra",
    [int]$WslMemoryGB = 32,
    [int]$WslSwapGB = 8,
    [int]$WslProcessors = 16,
    [int]$CheckIntervalMinutes = 5
)

$ErrorActionPreference = "Continue"

Write-Host @"

=============================================
  BIZRA Resource Guardian - Installer
  Optimizing NODE0 for Ihsan
=============================================

"@ -ForegroundColor Cyan

# ============================================================
# 1. Create directory structure
# ============================================================

Write-Host "[1/6] Setting up directory structure..." -ForegroundColor Yellow

$dirs = @("$InstallDir", "$InstallDir\logs", "$InstallDir\config")
foreach ($dir in $dirs) {
    if (-not (Test-Path $dir)) {
        New-Item -ItemType Directory -Path $dir -Force | Out-Null
    }
}

# Copy the guardian script
$guardianSource = Join-Path $PSScriptRoot "BIZRA-ResourceGuardian.ps1"
$guardianDest = Join-Path $InstallDir "BIZRA-ResourceGuardian.ps1"

if (Test-Path $guardianSource) {
    Copy-Item $guardianSource $guardianDest -Force
    Write-Host "  Guardian script installed to $guardianDest" -ForegroundColor Green
} else {
    Write-Host "  Guardian script not found at $guardianSource -- copy it manually to $guardianDest" -ForegroundColor Yellow
}

# ============================================================
# 2. Configure WSL2 memory limits
# ============================================================

Write-Host "[2/6] Configuring WSL2 resource limits..." -ForegroundColor Yellow

$wslConfig = @"
# BIZRA NODE0 - WSL2 Resource Configuration
# Generated by BIZRA Resource Guardian Installer
# Machine: 128 GB RAM / 32 cores / RTX 4090

[wsl2]
memory=${WslMemoryGB}GB
swap=${WslSwapGB}GB
processors=$WslProcessors

# Disable nested virtualization (save overhead unless needed)
nestedVirtualization=false
"@

$wslConfigPath = "$env:USERPROFILE\.wslconfig"
$wslBackup = "$env:USERPROFILE\.wslconfig.backup"

if (Test-Path $wslConfigPath) {
    Copy-Item $wslConfigPath $wslBackup -Force
    Write-Host "  Backed up existing .wslconfig" -ForegroundColor Green
}

Set-Content -Path $wslConfigPath -Value $wslConfig -Force
Write-Host "  WSL2 configured: ${WslMemoryGB}GB RAM, ${WslSwapGB}GB swap, $WslProcessors CPUs" -ForegroundColor Green
Write-Host "  Run 'wsl --shutdown' to apply WSL changes" -ForegroundColor Yellow

# ============================================================
# 3. Create Scheduled Tasks
# ============================================================

Write-Host "[3/6] Setting up scheduled tasks..." -ForegroundColor Yellow

# Task: Run Guardian on user login
$loginAction = New-ScheduledTaskAction `
    -Execute "powershell.exe" `
    -Argument "-NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File `"$guardianDest`" -DaemonMode -CheckIntervalSeconds 60"

$loginTrigger = New-ScheduledTaskTrigger -AtLogOn -User $env:USERNAME

$loginSettings = New-ScheduledTaskSettingsSet `
    -AllowStartIfOnBatteries `
    -DontStopIfGoingOnBatteries `
    -StartWhenAvailable `
    -RestartCount 3 `
    -RestartInterval (New-TimeSpan -Minutes 1) `
    -ExecutionTimeLimit (New-TimeSpan -Hours 0)

$loginPrincipal = New-ScheduledTaskPrincipal `
    -UserId $env:USERNAME `
    -LogonType Interactive `
    -RunLevel Highest

# Remove existing task if present
Unregister-ScheduledTask -TaskName "BIZRA-ResourceGuardian" -Confirm:$false -ErrorAction SilentlyContinue

Register-ScheduledTask `
    -TaskName "BIZRA-ResourceGuardian" `
    -Action $loginAction `
    -Trigger $loginTrigger `
    -Settings $loginSettings `
    -Principal $loginPrincipal `
    -Description "BIZRA Resource Guardian - Automated resource management for NODE0" `
    -ErrorAction Stop | Out-Null

Write-Host "  Login task registered: BIZRA-ResourceGuardian (daemon mode)" -ForegroundColor Green

# ============================================================
# 4. Disable unnecessary Windows scheduled tasks
# ============================================================

Write-Host "[4/6] Disabling unnecessary Windows tasks..." -ForegroundColor Yellow

$disableTasks = @(
    "\Microsoft\Windows\Application Experience\Microsoft Compatibility Appraiser",
    "\Microsoft\Windows\Application Experience\ProgramDataUpdater",
    "\Microsoft\Windows\Autochk\Proxy",
    "\Microsoft\Windows\Customer Experience Improvement Program\Consolidator",
    "\Microsoft\Windows\Customer Experience Improvement Program\UsbCeip",
    "\Microsoft\Windows\DiskDiagnostic\Microsoft-Windows-DiskDiagnosticDataCollector",
    "\Microsoft\Windows\Maps\MapsUpdateTask",
    "\Microsoft\Windows\Maps\MapsToastTask",
    "\Microsoft\Windows\Power Efficiency Diagnostics\AnalyzeSystem",
    "\Microsoft\Windows\Shell\FamilySafetyMonitor",
    "\Microsoft\Windows\Shell\FamilySafetyRefreshTask",
    "\Microsoft\Windows\Feedback\Siuf\DmClient",
    "\Microsoft\Windows\Windows Error Reporting\QueueReporting"
)

$disabledCount = 0
foreach ($task in $disableTasks) {
    try {
        Disable-ScheduledTask -TaskName $task -ErrorAction Stop | Out-Null
        $disabledCount++
    } catch {
        # Task may not exist
    }
}
Write-Host "  Disabled $disabledCount unnecessary Windows tasks" -ForegroundColor Green

# ============================================================
# 5. Power plan optimization
# ============================================================

Write-Host "[5/6] Optimizing power settings..." -ForegroundColor Yellow

try {
    # Set to High Performance
    $highPerf = powercfg /list | Select-String "High performance"
    if ($highPerf) {
        $guid = ($highPerf -split '\s+')[3]
        powercfg /setactive $guid
        Write-Host "  Power plan set to High Performance" -ForegroundColor Green
    } else {
        # Create ultimate performance plan
        powercfg /duplicatescheme e9a42b02-d5df-448d-aa00-03f14749eb61 2>$null
        Write-Host "  Ultimate Performance power plan activated" -ForegroundColor Green
    }

    # Disable USB selective suspend
    powercfg /setacvalueindex SCHEME_CURRENT 2a737441-1930-4402-8d77-b2bebba308a3 48e6b7a6-50f5-4782-a5d4-53bb8f07e226 0

    # Disable hard disk timeout
    powercfg /setacvalueindex SCHEME_CURRENT 0012ee47-9041-4b5d-9b77-535fba8b1442 6738e2c4-e8a5-4a42-b16a-e040e769756e 0

    powercfg /setactive SCHEME_CURRENT
    Write-Host "  USB suspend and disk timeout disabled" -ForegroundColor Green

} catch {
    Write-Host "  Could not fully optimize power settings: $($_.Exception.Message)" -ForegroundColor Yellow
}

# ============================================================
# 6. Create convenience scripts
# ============================================================

Write-Host "[6/6] Creating convenience scripts..." -ForegroundColor Yellow

# Quick status check script
$statusScript = @'
# BIZRA Guardian - Quick Status
$cpu = (Get-CimInstance Win32_Processor | Measure-Object LoadPercentage -Average).Average
$os = Get-CimInstance Win32_OperatingSystem
$memPct = [math]::Round((($os.TotalVisibleMemorySize - $os.FreePhysicalMemory) / $os.TotalVisibleMemorySize) * 100, 1)
$memUsed = [math]::Round(($os.TotalVisibleMemorySize - $os.FreePhysicalMemory) / 1MB, 1)
$memTotal = [math]::Round($os.TotalVisibleMemorySize / 1MB, 1)

$wslMem = (Get-Process -Name "vmmem*" -ErrorAction SilentlyContinue | Measure-Object WorkingSet64 -Sum).Sum
$wslGB = [math]::Round($wslMem / 1GB, 1)

$dockerMem = (Get-Process -Name "*docker*" -ErrorAction SilentlyContinue | Measure-Object WorkingSet64 -Sum).Sum
$dockerMB = [math]::Round($dockerMem / 1MB, 0)

Write-Host ""
Write-Host "=========================================" -ForegroundColor Cyan
Write-Host "     BIZRA NODE0 - System Status        " -ForegroundColor Cyan
Write-Host "=========================================" -ForegroundColor Cyan
$cpuColor = if($cpu -gt 80){"Red"}elseif($cpu -gt 50){"Yellow"}else{"Green"}
Write-Host ("  CPU:    {0,5}%" -f $cpu) -ForegroundColor $cpuColor
$memColor = if($memPct -gt 80){"Red"}elseif($memPct -gt 60){"Yellow"}else{"Green"}
Write-Host ("  RAM:    {0,5}% ({1}/{2} GB)" -f $memPct, $memUsed, $memTotal) -ForegroundColor $memColor
Write-Host ("  WSL:    {0,5} GB" -f $wslGB) -ForegroundColor Cyan
Write-Host ("  Docker: {0,5} MB" -f $dockerMB) -ForegroundColor Cyan
Write-Host "-----------------------------------------" -ForegroundColor Cyan

$guardianTask = Get-ScheduledTask -TaskName "BIZRA-ResourceGuardian" -ErrorAction SilentlyContinue
if ($guardianTask) {
    $state = $guardianTask.State
    $color = if ($state -eq "Running") { "Green" } else { "Yellow" }
    Write-Host "  Guardian: $state" -ForegroundColor $color
} else {
    Write-Host "  Guardian: NOT INSTALLED" -ForegroundColor Red
}
Write-Host "=========================================" -ForegroundColor Cyan
Write-Host ""
'@

Set-Content -Path "$InstallDir\status.ps1" -Value $statusScript
Write-Host "  Status script: $InstallDir\status.ps1" -ForegroundColor Green

# Manual trigger script
$manualScript = @"
# BIZRA Guardian - Manual Trigger
& "$guardianDest"
"@
Set-Content -Path "$InstallDir\run-guardian.ps1" -Value $manualScript
Write-Host "  Manual trigger: $InstallDir\run-guardian.ps1" -ForegroundColor Green

# Stop guardian script
$stopScript = @'
# Stop BIZRA Guardian daemon
$stopped = 0
Get-Process -Name "powershell","pwsh" -ErrorAction SilentlyContinue | ForEach-Object {
    try {
        $cmdLine = (Get-CimInstance Win32_Process -Filter "ProcessId=$($_.Id)").CommandLine
        if ($cmdLine -like "*BIZRA-ResourceGuardian*") {
            Stop-Process -Id $_.Id -Force
            $stopped++
        }
    } catch { }
}
if ($stopped -gt 0) {
    Write-Host "Guardian daemon stopped ($stopped processes)." -ForegroundColor Yellow
} else {
    Write-Host "No Guardian daemon running." -ForegroundColor DarkGray
}
'@
Set-Content -Path "$InstallDir\stop-guardian.ps1" -Value $stopScript
Write-Host "  Stop script: $InstallDir\stop-guardian.ps1" -ForegroundColor Green

# ============================================================
# SUMMARY
# ============================================================

Write-Host @"

=============================================
  Installation Complete
=============================================

  Install dir:  $InstallDir
  Logs:         $InstallDir\logs

  Auto-start:   On login (daemon mode, 60s cycle)
  WSL2 cap:     ${WslMemoryGB}GB RAM / ${WslSwapGB}GB swap / $WslProcessors CPUs
  Power plan:   High Performance

  Quick commands (run in PowerShell):
    Status:  . $InstallDir\status.ps1
    Manual:  . $InstallDir\run-guardian.ps1
    Stop:    . $InstallDir\stop-guardian.ps1

  REQUIRED: Run 'wsl --shutdown' then restart WSL

=============================================

"@ -ForegroundColor Cyan
