"""
BIZRA PROOF-CARRYING INFERENCE (PCI) PROTOCOL
Rejection Code Registry - Stable Numeric IDs
"""

from enum import IntEnum

class RejectCode(IntEnum):
    SUCCESS = 0
    REJECT_SCHEMA = 1
    REJECT_SIGNATURE = 2
    REJECT_NONCE_REPLAY = 3
    REJECT_TIMESTAMP_STALE = 4
    REJECT_TIMESTAMP_FUTURE = 5
    REJECT_IHSAN_BELOW_MIN = 6
    REJECT_SNR_BELOW_MIN = 7
    REJECT_BUDGET_EXCEEDED = 8
    REJECT_POLICY_MISMATCH = 9
    REJECT_STATE_MISMATCH = 10
    REJECT_ROLE_VIOLATION = 11
    REJECT_QUORUM_FAILED = 12
    REJECT_FATE_VIOLATION = 13
    REJECT_INVARIANT_FAILED = 14
    REJECT_RATE_LIMITED = 15
    REJECT_INTERNAL_ERROR = 99
