// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GateVerdictContract } from "./GateVerdictContract";
import type { RejectedClaimContract } from "./RejectedClaimContract";
import type { VerdictName } from "./VerdictName";

/**
 * Full admissibility verdict shipped by every mission endpoint.
 */
export type AdmissibilityContract = { verdict: VerdictName, gateVerdicts: Array<GateVerdictContract>, rejected: RejectedClaimContract | null, };
