// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VerdictName } from "./VerdictName";

/**
 * Gate verdict row as it appears inside AdmissibilityResult.
 */
export type GateVerdictContract = { scorerId: string, invariant: string | null, verdict: VerdictName, reason: string, score: number | null, };
