// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PoiPerKindContract } from "./PoiPerKindContract";

export type PoiSummaryResponseContract = { chainHead: string, totalEntries: number, totalImpact: number, avgImpact: number, maxImpact: number, byKind: Array<PoiPerKindContract>, };
