// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Canonical string name for a `ReceiptKind` at the HTTP boundary.
 * Matches the Rust enum 1:1 by naming convention.
 */
export type ReceiptKindName = "Genesis" | "CognitionBoot" | "Myelination" | "Demyelination" | "ReasoningSession" | "GovernanceDecision" | "NodeLifecycle" | "Manifest" | "PrincipalActivation" | "MissionExecuted" | "DegradedPath";
