// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Structured rejection detail when admissibility refuses a claim.
 */
export type RejectedClaimContract = { invariant: string, reason: string, remediationPath: string, escalationAllowed: boolean, };
