// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResourceContract } from "./ResourceContract";

export type UrpBucketContract = { kind: string, resources: Array<ResourceContract>, };
