// crates/bizra-gateway/src/lib.rs - WebSocket/REST Bridge
// Connects React UI (VΩ.3.0) to Rust Sovereign Kernel (VΩ.5.1)

use actix_web::http::StatusCode;
use actix_web::{web, App, HttpRequest, HttpResponse, HttpServer, Result as ActixResult};
// use actix_ws::Message; // Removed unused import
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use std::sync::Arc;
use tokio::sync::Mutex;
use tracing::info;
use uuid::Uuid;

/// VerifiedFrame POD (Plain Old Data) - The atomic unit of truth
/// Contains cryptographically signed, symbolically verified content
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VerifiedFrame {
    /// Unique frame identifier
    pub id: String,
    /// Decentralized Identifier (DID) for sovereignty
    pub did: String,
    /// Content generated by neural models
    pub content: String,
    /// Symbolic proof (Z3-generated, SHA256 hash for now)
    pub proof: Vec<u8>,
    /// Isnad Chain - Provenance tracking for truth
    pub isnad_chain: Vec<String>,
    /// Graph of Thoughts metadata
    pub got_branch: u32,
    pub got_depth: u32,
    /// Timestamp of verification
    pub timestamp: DateTime<Utc>,
}

/// FATE Sidecar Response (simulated symbolic verification)
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FATEResponse {
    pub verified: bool,
    pub proof: Vec<u8>,
    pub confidence: f64,
}

/// Bizra Gateway - Thin bridge between UI and Kernel
pub struct BizraGateway {
    /// In-memory frame storage
    frames: Arc<Mutex<Vec<VerifiedFrame>>>,
    /// Broadcast channel for real-time updates (State of the Art: Lock-free fan-out)
    tx: tokio::sync::broadcast::Sender<VerifiedFrame>,
}

impl BizraGateway {
    pub fn new() -> Self {
        info!("🖥️  Initializing BIZRA Gateway - React ↔ Rust Bridge (Broadcast Mode)");

        let (tx, _rx) = tokio::sync::broadcast::channel(100); // Buffer size 100

        Self {
            frames: Arc::new(Mutex::new(Vec::new())),
            tx,
        }
    }

    /// Start the gateway server
    pub async fn start_server(self, port: u16) -> std::io::Result<()> {
        let gateway = Arc::new(self); // No Mutex needed for gateway structure itself now

        info!("🚀 Starting BIZRA Gateway on http://127.0.0.1:{}", port);

        HttpServer::new(move || {
            let gateway_clone = gateway.clone();

            App::new()
                .app_data(web::Data::new(gateway_clone))
                .route("/ws", web::get().to(ws_handler))
                .route("/frames", web::get().to(get_frames))
                .route("/frames", web::post().to(post_frame))
                .route("/health", web::get().to(health_check))
        })
        .bind(("127.0.0.1", port))?
        .run()
        .await
    }

    /// Simulate FATE Sidecar symbolic verification (would call Z3 in full impl)
    pub async fn verify_frame(&self, content: &str) -> FATEResponse {
        use sha2::{Digest, Sha256};
        let mut hasher = Sha256::new();
        hasher.update(content.as_bytes());
        let proof = hasher.finalize().to_vec();
        let confidence = (content.len() as f64 / 1000.0).min(1.0);

        FATEResponse {
            verified: confidence > 0.3,
            proof,
            confidence,
        }
    }

    /// Add verified frame and broadcast to WebSocket clients
    pub async fn add_verified_frame(&self, frame: VerifiedFrame) {
        // Store frame
        {
            let mut frames = self.frames.lock().await;
            frames.push(frame.clone());
        }

        // Broadcast to all active subscribers via channel (Zero-Copy-ish logic)
        // We drop error if no subscribers, that's fine
        let _ = self.tx.send(frame);
    }

    /// Get all frames
    pub async fn get_frames(&self) -> Vec<VerifiedFrame> {
        self.frames.lock().await.clone()
    }
}

/// WebSocket handler for real-time frame streaming
async fn ws_handler(
    req: HttpRequest,
    stream: web::Payload,
    gateway: web::Data<Arc<BizraGateway>>,
) -> ActixResult<HttpResponse> {
    let (res, mut session, _stream) = actix_ws::handle(&req, stream)?;

    let mut rx = gateway.tx.subscribe();

    actix_web::rt::spawn(async move {
        loop {
            tokio::select! {
                // Handle broadcast messages
                Ok(frame) = rx.recv() => {
                    if let Ok(json) = serde_json::to_string(&frame) {
                        if session.text(json).await.is_err() {
                            break;
                        }
                    }
                }
                // Handle client heartbeat/close (placeholder for keepalive)
                _ = tokio::time::sleep(std::time::Duration::from_millis(100)) => {
                   // Keep loop alive
                }
            }
        }
    });

    Ok(res)
}

/// REST API: Get all verified frames
async fn get_frames(gateway: web::Data<Arc<BizraGateway>>) -> ActixResult<HttpResponse> {
    // No lock needed to get the gateway, but we lock the frames vec
    // Optimization: In a real "Elite" system, we'd use dashmap or RwLock for frames too.
    // For now, simple mutex on data is fine, but gateway itself is not mutexed.
    let frames = gateway.get_frames().await;
    Ok(HttpResponse::Ok().json(frames))
}

/// REST API: Post new frame for verification
async fn post_frame(
    frame_req: web::Json<serde_json::Value>,
    gateway: web::Data<Arc<BizraGateway>>,
) -> ActixResult<HttpResponse> {
    let content = frame_req
        .get("content")
        .and_then(|v| v.as_str())
        .unwrap_or("");

    // Verify with FATE Sidecar - this is async and lock-free on the gateway!
    let fate_response = gateway.verify_frame(content).await;

    if fate_response.verified {
        // Create VerifiedFrame
        let frame = VerifiedFrame {
            id: Uuid::new_v4().to_string(),
            did: format!("did:bizra:{}", Uuid::new_v4()),
            content: content.to_string(),
            proof: fate_response.proof,
            isnad_chain: vec!["gateway".to_string(), "fate_sidecar".to_string()],
            got_branch: 1,
            got_depth: 1,
            timestamp: Utc::now(),
        };

        // Add and broadcast
        gateway.add_verified_frame(frame.clone()).await;

        Ok(HttpResponse::Created().json(frame))
    } else {
        Ok(HttpResponse::BadRequest().json(serde_json::json!({
            "error": "Frame verification failed",
            "confidence": fate_response.confidence
        })))
    }
}

/// Health check endpoint
async fn health_check() -> ActixResult<HttpResponse> {
    Ok(HttpResponse::Ok().json(serde_json::json!({
        "status": "healthy",
        "version": "0.1.0",
        "description": "BIZRA Gateway - React ↔ Rust Sovereign Kernel Bridge"
    })))
}

#[cfg(test)]
mod tests {
    use super::*;
    use actix_web::test;

    #[tokio::test]
    async fn test_frame_verification() {
        let gateway = BizraGateway::new();
        let response = gateway.verify_frame("Test content").await;

        assert!(response.proof.len() > 0);
        assert!(response.confidence >= 0.0 && response.confidence <= 1.0);
    }

    #[tokio::test]
    async fn test_verified_frame_creation() {
        let gateway = BizraGateway::new();
        let frame = VerifiedFrame {
            id: "test-id".to_string(),
            did: "did:test:123".to_string(),
            content: "Test content".to_string(),
            proof: vec![1, 2, 3],
            isnad_chain: vec!["test".to_string()],
            got_branch: 1,
            got_depth: 1,
            timestamp: Utc::now(),
        };

        gateway.add_verified_frame(frame.clone()).await;
        let frames = gateway.get_frames().await;

        assert_eq!(frames.len(), 1);
        assert_eq!(frames[0].id, "test-id");
    }

    #[actix_rt::test]
    async fn test_gateway_round_trip() {
        let gateway = Arc::new(BizraGateway::new());
        let app = test::init_service(BizraGateway::build_app(gateway)).await;

        let payload = serde_json::json!({ "content": "hello-world" });
        let req = test::TestRequest::post()
            .uri("/frames")
            .set_json(&payload)
            .to_request();

        let resp = test::call_service(&app, req).await;
        assert_eq!(resp.status(), StatusCode::CREATED);
        let created: VerifiedFrame = test::read_body_json(resp).await;
        assert_eq!(created.content, "hello-world");

        let list_req = test::TestRequest::get().uri("/frames").to_request();
        let list_resp = test::call_service(&app, list_req).await;
        assert_eq!(list_resp.status(), StatusCode::OK);
        let frames: Vec<VerifiedFrame> = test::read_body_json(list_resp).await;
        assert_eq!(frames.len(), 1);
        assert_eq!(frames[0].id, created.id);
    }
}
