// src/ollama.rs - Ollama Local LLM Integration
//
// Connects to local Ollama instance for:
// - Text generation (generate endpoint)
// - Chat completion (chat endpoint)  
// - Embeddings generation (embeddings endpoint)
//
// Environment variables:
// - OLLAMA_URL: Base URL (default: http://localhost:11434)
// - OLLAMA_MODEL: Default model (default: llama3.2)

use lazy_static::lazy_static;
use prometheus::{register_counter_vec, register_gauge, register_histogram_vec, CounterVec, Gauge, HistogramVec};
use reqwest::Client;
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::sync::Arc;
use std::time::{Duration, Instant};
use tokio::sync::OnceCell;
use tracing::{debug, error, info, instrument, warn};

/// Default Ollama server URL
const DEFAULT_OLLAMA_URL: &str = "http://localhost:11434";

/// Default model for generation
const DEFAULT_MODEL: &str = "llama3.2";

/// Request timeout for Ollama API calls
const REQUEST_TIMEOUT: Duration = Duration::from_secs(120);

/// Maximum tokens for generation
const DEFAULT_MAX_TOKENS: u32 = 2048;

lazy_static! {
    /// Ollama API call counter
    pub static ref OLLAMA_REQUESTS: CounterVec = register_counter_vec!(
        "bizra_ollama_requests_total",
        "Total Ollama API requests",
        &["endpoint", "model", "result"]  // generate/chat/embeddings, model name, success/error
    ).unwrap();
    
    /// Ollama generation latency
    pub static ref OLLAMA_LATENCY: HistogramVec = register_histogram_vec!(
        "bizra_ollama_latency_seconds",
        "Ollama API latency in seconds",
        &["endpoint", "model"],
        vec![0.1, 0.5, 1.0, 2.5, 5.0, 10.0, 30.0, 60.0, 120.0]
    ).unwrap();
    
    /// Ollama connection status
    pub static ref OLLAMA_CONNECTED: Gauge = register_gauge!(
        "bizra_ollama_connected",
        "Ollama connection status (1=connected, 0=disconnected)"
    ).unwrap();
    
    /// Ollama tokens generated
    pub static ref OLLAMA_TOKENS: CounterVec = register_counter_vec!(
        "bizra_ollama_tokens_total",
        "Total tokens generated by Ollama",
        &["type", "model"]  // prompt/completion, model
    ).unwrap();
}

/// Global Ollama client singleton
static OLLAMA_CLIENT: OnceCell<Arc<OllamaClient>> = OnceCell::const_new();

/// Get or create the global Ollama client
pub async fn get_ollama() -> Arc<OllamaClient> {
    OLLAMA_CLIENT
        .get_or_init(|| async {
            let client = OllamaClient::from_env().await;
            Arc::new(client)
        })
        .await
        .clone()
}

/// Ollama API Error
#[derive(Debug, thiserror::Error)]
pub enum OllamaError {
    #[error("HTTP error: {0}")]
    Http(#[from] reqwest::Error),
    
    #[error("Invalid response: {0}")]
    InvalidResponse(String),
    
    #[error("Model not found: {0}")]
    ModelNotFound(String),
    
    #[error("Connection failed: {0}")]
    ConnectionFailed(String),
    
    #[error("Generation timeout")]
    Timeout,
}

/// Chat message for Ollama chat API
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatMessage {
    pub role: String,  // system, user, assistant
    pub content: String,
}

impl ChatMessage {
    pub fn system(content: impl Into<String>) -> Self {
        Self { role: "system".to_string(), content: content.into() }
    }
    
    pub fn user(content: impl Into<String>) -> Self {
        Self { role: "user".to_string(), content: content.into() }
    }
    
    pub fn assistant(content: impl Into<String>) -> Self {
        Self { role: "assistant".to_string(), content: content.into() }
    }
}

/// Generation options
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct GenerationOptions {
    pub temperature: Option<f64>,
    pub top_p: Option<f64>,
    pub top_k: Option<u32>,
    pub num_ctx: Option<u32>,
    pub num_predict: Option<u32>,
    pub repeat_penalty: Option<f64>,
    pub seed: Option<i64>,
    pub stop: Option<Vec<String>>,
}

/// Generate response from Ollama
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GenerateResponse {
    pub model: String,
    pub response: String,
    pub done: bool,
    pub context: Option<Vec<i64>>,
    pub total_duration: Option<u64>,
    pub load_duration: Option<u64>,
    pub prompt_eval_count: Option<u32>,
    pub prompt_eval_duration: Option<u64>,
    pub eval_count: Option<u32>,
    pub eval_duration: Option<u64>,
}

/// Chat response from Ollama
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatResponse {
    pub model: String,
    pub message: ChatMessage,
    pub done: bool,
    pub total_duration: Option<u64>,
    pub load_duration: Option<u64>,
    pub prompt_eval_count: Option<u32>,
    pub eval_count: Option<u32>,
}

/// Embeddings response from Ollama
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EmbeddingsResponse {
    pub model: String,
    pub embeddings: Vec<Vec<f64>>,
    pub total_duration: Option<u64>,
    pub load_duration: Option<u64>,
    pub prompt_eval_count: Option<u32>,
}

/// Model info from Ollama
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ModelInfo {
    pub name: String,
    pub model: String,
    pub modified_at: String,
    pub size: u64,
    pub digest: String,
    pub details: Option<ModelDetails>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ModelDetails {
    pub parent_model: Option<String>,
    pub format: Option<String>,
    pub family: Option<String>,
    pub families: Option<Vec<String>>,
    pub parameter_size: Option<String>,
    pub quantization_level: Option<String>,
}

/// Ollama Client
pub struct OllamaClient {
    base_url: String,
    default_model: String,
    http: Client,
    connected: bool,
}

impl OllamaClient {
    /// Create new client with explicit configuration
    pub fn new(base_url: String, default_model: String) -> Self {
        let http = Client::builder()
            .timeout(REQUEST_TIMEOUT)
            .build()
            .expect("Failed to create HTTP client");
        
        Self {
            base_url,
            default_model,
            http,
            connected: false,
        }
    }
    
    /// Create client from environment variables
    pub async fn from_env() -> Self {
        let base_url = std::env::var("OLLAMA_URL")
            .unwrap_or_else(|_| DEFAULT_OLLAMA_URL.to_string());
        let default_model = std::env::var("OLLAMA_MODEL")
            .unwrap_or_else(|_| DEFAULT_MODEL.to_string());
        
        let mut client = Self::new(base_url.clone(), default_model);
        
        // Test connection
        match client.health_check().await {
            Ok(_) => {
                info!("🦙 Ollama connected at {}", base_url);
                client.connected = true;
                OLLAMA_CONNECTED.set(1.0);
            }
            Err(e) => {
                warn!("⚠️ Ollama not available at {}: {}", base_url, e);
                client.connected = false;
                OLLAMA_CONNECTED.set(0.0);
            }
        }
        
        client
    }
    
    /// Check if Ollama is connected
    pub fn is_connected(&self) -> bool {
        self.connected
    }
    
    /// Health check - verify Ollama is running
    #[instrument(skip(self))]
    pub async fn health_check(&self) -> Result<(), OllamaError> {
        let url = format!("{}/api/tags", self.base_url);
        
        let resp = self.http.get(&url).send().await?;
        
        if resp.status().is_success() {
            Ok(())
        } else {
            Err(OllamaError::ConnectionFailed(format!(
                "Status: {}", resp.status()
            )))
        }
    }
    
    /// List available models
    #[instrument(skip(self))]
    pub async fn list_models(&self) -> Result<Vec<ModelInfo>, OllamaError> {
        let url = format!("{}/api/tags", self.base_url);
        
        let resp = self.http.get(&url).send().await?;
        let data: serde_json::Value = resp.json().await?;
        
        let models: Vec<ModelInfo> = data
            .get("models")
            .and_then(|m| serde_json::from_value(m.clone()).ok())
            .unwrap_or_default();
        
        debug!("Found {} Ollama models", models.len());
        Ok(models)
    }
    
    /// Generate text completion
    #[instrument(skip(self, options))]
    pub async fn generate(
        &self,
        prompt: &str,
        model: Option<&str>,
        options: Option<GenerationOptions>,
    ) -> Result<GenerateResponse, OllamaError> {
        let start = Instant::now();
        let model = model.unwrap_or(&self.default_model);
        let url = format!("{}/api/generate", self.base_url);
        
        let mut body = serde_json::json!({
            "model": model,
            "prompt": prompt,
            "stream": false,
        });
        
        // Apply options
        if let Some(opts) = options {
            let mut options_map = serde_json::Map::new();
            if let Some(t) = opts.temperature {
                options_map.insert("temperature".to_string(), serde_json::json!(t));
            }
            if let Some(p) = opts.top_p {
                options_map.insert("top_p".to_string(), serde_json::json!(p));
            }
            if let Some(k) = opts.top_k {
                options_map.insert("top_k".to_string(), serde_json::json!(k));
            }
            if let Some(ctx) = opts.num_ctx {
                options_map.insert("num_ctx".to_string(), serde_json::json!(ctx));
            }
            if let Some(predict) = opts.num_predict {
                options_map.insert("num_predict".to_string(), serde_json::json!(predict));
            }
            if let Some(penalty) = opts.repeat_penalty {
                options_map.insert("repeat_penalty".to_string(), serde_json::json!(penalty));
            }
            if let Some(seed) = opts.seed {
                options_map.insert("seed".to_string(), serde_json::json!(seed));
            }
            if !options_map.is_empty() {
                body["options"] = serde_json::Value::Object(options_map);
            }
            if let Some(stop) = opts.stop {
                body["stop"] = serde_json::json!(stop);
            }
        }
        
        debug!("Calling Ollama generate: model={}", model);
        
        let resp = self.http.post(&url).json(&body).send().await?;
        let latency = start.elapsed();
        
        OLLAMA_LATENCY
            .with_label_values(&["generate", model])
            .observe(latency.as_secs_f64());
        
        if !resp.status().is_success() {
            let status = resp.status();
            let error_text = resp.text().await.unwrap_or_default();
            OLLAMA_REQUESTS.with_label_values(&["generate", model, "error"]).inc();
            
            if error_text.contains("model") && error_text.contains("not found") {
                return Err(OllamaError::ModelNotFound(model.to_string()));
            }
            
            return Err(OllamaError::InvalidResponse(format!(
                "Status {}: {}", status, error_text
            )));
        }
        
        let response: GenerateResponse = resp.json().await?;
        
        // Record metrics
        OLLAMA_REQUESTS.with_label_values(&["generate", model, "success"]).inc();
        
        if let Some(prompt_tokens) = response.prompt_eval_count {
            OLLAMA_TOKENS
                .with_label_values(&["prompt", model])
                .inc_by(prompt_tokens as f64);
        }
        if let Some(completion_tokens) = response.eval_count {
            OLLAMA_TOKENS
                .with_label_values(&["completion", model])
                .inc_by(completion_tokens as f64);
        }
        
        debug!(
            "Ollama generate completed in {:.2}s, {} tokens",
            latency.as_secs_f64(),
            response.eval_count.unwrap_or(0)
        );
        
        Ok(response)
    }
    
    /// Chat completion with message history
    #[instrument(skip(self, messages, options))]
    pub async fn chat(
        &self,
        messages: Vec<ChatMessage>,
        model: Option<&str>,
        options: Option<GenerationOptions>,
    ) -> Result<ChatResponse, OllamaError> {
        let start = Instant::now();
        let model = model.unwrap_or(&self.default_model);
        let url = format!("{}/api/chat", self.base_url);
        
        let mut body = serde_json::json!({
            "model": model,
            "messages": messages,
            "stream": false,
        });
        
        // Apply options
        if let Some(opts) = options {
            let mut options_map = serde_json::Map::new();
            if let Some(t) = opts.temperature {
                options_map.insert("temperature".to_string(), serde_json::json!(t));
            }
            if let Some(p) = opts.top_p {
                options_map.insert("top_p".to_string(), serde_json::json!(p));
            }
            if let Some(k) = opts.top_k {
                options_map.insert("top_k".to_string(), serde_json::json!(k));
            }
            if let Some(ctx) = opts.num_ctx {
                options_map.insert("num_ctx".to_string(), serde_json::json!(ctx));
            }
            if let Some(predict) = opts.num_predict {
                options_map.insert("num_predict".to_string(), serde_json::json!(predict));
            }
            if !options_map.is_empty() {
                body["options"] = serde_json::Value::Object(options_map);
            }
        }
        
        debug!("Calling Ollama chat: model={}, messages={}", model, messages.len());
        
        let resp = self.http.post(&url).json(&body).send().await?;
        let latency = start.elapsed();
        
        OLLAMA_LATENCY
            .with_label_values(&["chat", model])
            .observe(latency.as_secs_f64());
        
        if !resp.status().is_success() {
            let status = resp.status();
            let error_text = resp.text().await.unwrap_or_default();
            OLLAMA_REQUESTS.with_label_values(&["chat", model, "error"]).inc();
            
            return Err(OllamaError::InvalidResponse(format!(
                "Status {}: {}", status, error_text
            )));
        }
        
        let response: ChatResponse = resp.json().await?;
        
        OLLAMA_REQUESTS.with_label_values(&["chat", model, "success"]).inc();
        
        if let Some(prompt_tokens) = response.prompt_eval_count {
            OLLAMA_TOKENS
                .with_label_values(&["prompt", model])
                .inc_by(prompt_tokens as f64);
        }
        if let Some(completion_tokens) = response.eval_count {
            OLLAMA_TOKENS
                .with_label_values(&["completion", model])
                .inc_by(completion_tokens as f64);
        }
        
        debug!(
            "Ollama chat completed in {:.2}s",
            latency.as_secs_f64()
        );
        
        Ok(response)
    }
    
    /// Generate embeddings for text
    #[instrument(skip(self, input))]
    pub async fn embeddings(
        &self,
        input: Vec<String>,
        model: Option<&str>,
    ) -> Result<EmbeddingsResponse, OllamaError> {
        let start = Instant::now();
        let model = model.unwrap_or("nomic-embed-text"); // Default embedding model
        let url = format!("{}/api/embed", self.base_url);
        
        let body = serde_json::json!({
            "model": model,
            "input": input,
        });
        
        debug!("Calling Ollama embeddings: model={}, inputs={}", model, input.len());
        
        let resp = self.http.post(&url).json(&body).send().await?;
        let latency = start.elapsed();
        
        OLLAMA_LATENCY
            .with_label_values(&["embeddings", model])
            .observe(latency.as_secs_f64());
        
        if !resp.status().is_success() {
            let status = resp.status();
            let error_text = resp.text().await.unwrap_or_default();
            OLLAMA_REQUESTS.with_label_values(&["embeddings", model, "error"]).inc();
            
            return Err(OllamaError::InvalidResponse(format!(
                "Status {}: {}", status, error_text
            )));
        }
        
        let response: EmbeddingsResponse = resp.json().await?;
        
        OLLAMA_REQUESTS.with_label_values(&["embeddings", model, "success"]).inc();
        
        debug!(
            "Ollama embeddings completed in {:.2}s, {} vectors",
            latency.as_secs_f64(),
            response.embeddings.len()
        );
        
        Ok(response)
    }
    
    /// Pull a model from Ollama registry
    #[instrument(skip(self))]
    pub async fn pull_model(&self, model: &str) -> Result<(), OllamaError> {
        let url = format!("{}/api/pull", self.base_url);
        
        info!("📥 Pulling Ollama model: {}", model);
        
        let body = serde_json::json!({
            "name": model,
            "stream": false,
        });
        
        let resp = self.http.post(&url).json(&body).send().await?;
        
        if resp.status().is_success() {
            info!("✅ Model {} pulled successfully", model);
            Ok(())
        } else {
            let error = resp.text().await.unwrap_or_default();
            Err(OllamaError::InvalidResponse(error))
        }
    }
    
    /// Get BIZRA-optimized system prompt
    pub fn bizra_system_prompt() -> String {
        r#"You are an AI assistant operating within the BIZRA META ALPHA ELITE system.

CORE PRINCIPLES:
1. IHSĀN (Excellence): Every response must achieve the highest quality standard
2. SAFETY: Never produce harmful, dangerous, or unethical content
3. TRUTHFULNESS: Be grounded in facts; acknowledge uncertainty
4. HELPFULNESS: Prioritize user benefit while maintaining safety

OPERATIONAL CONTEXT:
- Your responses pass through the SAT (Self-Assessment Tribunal)
- A 3/5 validator consensus is required for approval
- Ihsān score ≥ 0.92 (CI) or 0.85 (local) required

RESPONSE GUIDELINES:
- Be concise yet comprehensive
- Structure complex answers clearly
- Cite sources when possible
- Flag any limitations or uncertainties"#.to_string()
    }
    
    /// Execute BIZRA-enhanced generation with SAPE integration
    #[instrument(skip(self))]
    pub async fn bizra_generate(
        &self,
        prompt: &str,
        model: Option<&str>,
    ) -> Result<GenerateResponse, OllamaError> {
        let system_prompt = Self::bizra_system_prompt();
        let full_prompt = format!("{}\n\nUser Query:\n{}", system_prompt, prompt);
        
        let options = GenerationOptions {
            temperature: Some(0.7),
            top_p: Some(0.9),
            num_predict: Some(DEFAULT_MAX_TOKENS),
            repeat_penalty: Some(1.1),
            ..Default::default()
        };
        
        self.generate(&full_prompt, model, Some(options)).await
    }
    
    /// Execute BIZRA-enhanced chat with context
    #[instrument(skip(self, history))]
    pub async fn bizra_chat(
        &self,
        user_message: &str,
        history: Vec<ChatMessage>,
        model: Option<&str>,
    ) -> Result<ChatResponse, OllamaError> {
        let mut messages = vec![ChatMessage::system(Self::bizra_system_prompt())];
        messages.extend(history);
        messages.push(ChatMessage::user(user_message));
        
        let options = GenerationOptions {
            temperature: Some(0.7),
            top_p: Some(0.9),
            num_predict: Some(DEFAULT_MAX_TOKENS),
            ..Default::default()
        };
        
        self.chat(messages, model, Some(options)).await
    }
}

/// Ollama fallback for when service is unavailable
pub struct OllamaFallback;

impl OllamaFallback {
    /// Return simulated response when Ollama is unavailable
    pub fn simulated_response(prompt: &str) -> GenerateResponse {
        warn!("⚠️ Ollama unavailable, returning simulated response");
        
        GenerateResponse {
            model: "simulated".to_string(),
            response: format!(
                "[SIMULATED] Ollama is not available. Your prompt was: '{}'",
                &prompt[..prompt.len().min(100)]
            ),
            done: true,
            context: None,
            total_duration: Some(0),
            load_duration: Some(0),
            prompt_eval_count: Some(0),
            prompt_eval_duration: Some(0),
            eval_count: Some(0),
            eval_duration: Some(0),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    
    #[test]
    fn test_chat_message_construction() {
        let system = ChatMessage::system("You are helpful");
        assert_eq!(system.role, "system");
        
        let user = ChatMessage::user("Hello");
        assert_eq!(user.role, "user");
        
        let assistant = ChatMessage::assistant("Hi there!");
        assert_eq!(assistant.role, "assistant");
    }
    
    #[test]
    fn test_generation_options() {
        let opts = GenerationOptions {
            temperature: Some(0.8),
            top_p: Some(0.95),
            num_predict: Some(1024),
            ..Default::default()
        };
        
        assert_eq!(opts.temperature, Some(0.8));
        assert!(opts.seed.is_none());
    }
    
    #[test]
    fn test_bizra_system_prompt() {
        let prompt = OllamaClient::bizra_system_prompt();
        
        assert!(prompt.contains("IHSĀN"));
        assert!(prompt.contains("SAT"));
        assert!(prompt.contains("0.92"));
    }
    
    #[test]
    fn test_fallback_response() {
        let response = OllamaFallback::simulated_response("Test prompt");
        
        assert_eq!(response.model, "simulated");
        assert!(response.response.contains("SIMULATED"));
        assert!(response.done);
    }
    
    #[tokio::test]
    async fn test_client_from_env() {
        // This tests the client creation, not actual connection
        std::env::set_var("OLLAMA_URL", "http://test:11434");
        std::env::set_var("OLLAMA_MODEL", "test-model");
        
        let client = OllamaClient::new(
            "http://test:11434".to_string(),
            "test-model".to_string(),
        );
        
        assert_eq!(client.default_model, "test-model");
        assert!(!client.is_connected()); // Won't be connected in tests
    }
}
