from __future__ import annotations

from pathlib import Path

from scripts.ci_dependency_governance import validate_dependency_governance


def _write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def test_dependency_governance_accepts_aligned_contract(tmp_path: Path) -> None:
    pyproject = tmp_path / "pyproject.toml"
    requirements = tmp_path / "requirements.txt"
    lock = tmp_path / "requirements.lock"

    _write(
        pyproject,
        """
[project]
dependencies = [
    "httpx>=0.24.0,<1.0",
    "mcp[cli]>=1.0.0,<2.0",
]
""".strip(),
    )
    _write(
        requirements,
        """
httpx>=0.24.0,<1.0
mcp[cli]>=1.0.0,<2.0
""".strip(),
    )
    _write(
        lock,
        """
# This file was autogenerated by uv via the following command:
httpx==0.28.1
    --hash=sha256:abc
mcp==1.25.0
    --hash=sha256:def
""".strip(),
    )

    report = validate_dependency_governance(pyproject, requirements, lock)

    assert report.ok, report.format()


def test_dependency_governance_reports_requirements_txt_drift(tmp_path: Path) -> None:
    pyproject = tmp_path / "pyproject.toml"
    requirements = tmp_path / "requirements.txt"
    lock = tmp_path / "requirements.lock"

    _write(
        pyproject,
        """
[project]
dependencies = [
    "plotly>=5.15.0,<6.0",
]
""".strip(),
    )
    _write(requirements, "plotly>=5.15.0\n")
    _write(
        lock,
        """
# This file was autogenerated by uv via the following command:
plotly==5.24.1
    --hash=sha256:abc
""".strip(),
    )

    report = validate_dependency_governance(pyproject, requirements, lock)

    assert not report.ok
    assert any("requirements.txt drifted" in issue for issue in report.issues)


def test_dependency_governance_rejects_editable_or_vcs_lock_entries(
    tmp_path: Path,
) -> None:
    pyproject = tmp_path / "pyproject.toml"
    requirements = tmp_path / "requirements.txt"
    lock = tmp_path / "requirements.lock"

    _write(
        pyproject,
        """
[project]
dependencies = [
    "httpx>=0.24.0,<1.0",
]
""".strip(),
    )
    _write(requirements, "httpx>=0.24.0,<1.0\n")
    _write(
        lock,
        """
# This file was autogenerated by uv via the following command:
-e git+https://example.com/repo.git#egg=bad
httpx==0.28.1
    --hash=sha256:abc
""".strip(),
    )

    report = validate_dependency_governance(pyproject, requirements, lock)

    assert not report.ok
    assert any("editable or VCS" in issue for issue in report.issues)


def test_dependency_governance_rejects_unhashed_lock_entries(tmp_path: Path) -> None:
    pyproject = tmp_path / "pyproject.toml"
    requirements = tmp_path / "requirements.txt"
    lock = tmp_path / "requirements.lock"

    _write(
        pyproject,
        """
[project]
dependencies = [
    "httpx>=0.24.0,<1.0",
]
""".strip(),
    )
    _write(requirements, "httpx>=0.24.0,<1.0\n")
    _write(
        lock,
        """
# This file was autogenerated by uv via the following command:
httpx==0.28.1
""".strip(),
    )

    report = validate_dependency_governance(pyproject, requirements, lock)

    assert not report.ok
    assert any("not hash-pinned" in issue for issue in report.issues)


def test_dependency_governance_rejects_lock_pin_outside_declared_range(
    tmp_path: Path,
) -> None:
    pyproject = tmp_path / "pyproject.toml"
    requirements = tmp_path / "requirements.txt"
    lock = tmp_path / "requirements.lock"

    _write(
        pyproject,
        """
[project]
dependencies = [
    "plotly>=5.15.0,<6.0",
]
""".strip(),
    )
    _write(requirements, "plotly>=5.15.0,<6.0\n")
    _write(
        lock,
        """
# This file was autogenerated by uv via the following command:
plotly==6.5.0
    --hash=sha256:abc
""".strip(),
    )

    report = validate_dependency_governance(pyproject, requirements, lock)

    assert not report.ok
    assert any("violates declared constraint" in issue for issue in report.issues)
